### PR TITLE
Fix wrong link to class-name-casing doc in readme

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by j-f1** [comment]
See also #72.

**Comment by mightyiam** [comment]
@j-f1 should I do something about that, or does it render this PR obsolete?

**Comment by weirdpattern** [comment]
I would just close this PR in favor of avoiding merge conflicts with @j-f1's PR...

**Comment by weirdpattern** [comment]
@mightyiam can we close this PR? Your change is already included in @j-f1's eslint-docs PR and we usually merge PRs in chronological order so there is no real reason to keep this one open.

**Pull request closed without merging**
