### PR TITLE
Chore: Add husky precommit hook (fixes #51)

### LINKED ISSUE #51: Adding a pre-commit hook to execute lint and tests
I think we all could benefit from having a pre-commit hook to make sure everything is in order before committing our code. If everybody is ok with this, I would like to add [pre-commit](https://www.npmjs.com/package/pre-commit) to the project...

Of course I'm open to suggestions in case anyone has a better idea 😄

### PR DESCRIPTION
**Pull request by weirdpattern**
Adds husky precommit hook to validate tests and lint code before committing.

### CODE REVIEW

**Comment by weirdpattern** [comment]
gladly!

**Comment by JamesHenry** [comment]
The prettier PR has now been merged!

cc @aboyton

**Comment by weirdpattern** [comment]
I will do this tonight!

**Comment by weirdpattern** [comment]
@JamesHenry done!

**Comment by JamesHenry** [comment]
Thanks! I have changed the order - first tests, then lint-staged

**Pull request merged**
