### PR TITLE
New: Add adjacent-overload-signatures

### PR DESCRIPTION
**Pull request by weirdpattern**
This includes

New rule adjacent-overload-signatures
Corresponding test
Corresponding documentation
Update to README.md to include the new rule

Related to #5 (TSLint compatibility)

### CODE REVIEW

**Comment by weirdpattern** [comment]
Hmm.. I will rebase this tonight and fix the lint issue.. I probably fat-fingered something...

**Comment by weirdpattern** [comment]
Ok, rebased and linted...

**Comment by JamesHenry** [comment]
Thanks!

**Comment by JamesHenry** [comment]
Published as 0.5.0

**Pull request merged**
