### PR TITLE
Add `typescript/no-unused-vars` rule to documentation (fixes #33)

### LINKED ISSUE #33: Improve documentation for `typescript/no-unused-vars`
There are several use cases `typescript/no-unused-vars` does not yet support, such as `type` declarations:

``` ts
type Foo = string;
// unexpected error
const foo: Foo = 'foo';
```

Would it be possible to track the status of this somewhere in the documentation? The docs for `typescript/no-unused-vars` do not make any mention of this.

I would be happy to raise a PR, but I don't know the full details of what is and isn't supported.

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by weirdpattern** [comment]
Thank you for your contribution @OliverJAsh, do you mind updating the title to include the bug you are fixing with this PR? We normally follow [eslint PR guidelines](http://eslint.org/docs/developer-guide/contributing/pull-requests).

**Comment by OliverJAsh** [comment]
@weirdpattern How does this look now? :-)

**Comment by weirdpattern** [comment]
@OliverJAsh Perfect!

**Comment by JamesHenry** [comment]
Sorry for the conflict, @OliverJAsh I just merged an older PR. As soon as this is rebased it will be good to go 👍  Thanks for your help!

**Comment by OliverJAsh** [comment]
@JamesHenry Done!

**Pull request merged**
