### PR TITLE
Fix: type-annotation-spacing rule doesn't work for class properties (fixes #24)

### LINKED ISSUE #24: type-annotation-spacing rule doesn't work for class properties
```
export class HelloComponent {
    title : string = 'Hello :)';
}
```

### PR DESCRIPTION
**Pull request by weirdpattern**
This change improves the existing type-annotation-spacing rule by adding:
- Support for class properties and methods
- Support for interfaces properties and methods
- Add options to control the spacings before and after the colon

### CODE REVIEW

**Comment by corbinu** [comment]
LGTM

**Comment by JamesHenry** [comment]
Thanks!

**Comment by JamesHenry** [comment]
I just published version 0.4.0 to npm and this PR is included in it 👍

**Comment by weirdpattern** [comment]
@JamesHenry Are we tagging the releases?

**Pull request merged**
