### PR TITLE
Fix: Mark qualified name type annotations as used

### PR DESCRIPTION
**Pull request by timothykang**

### CODE REVIEW

**Comment by timothykang** [comment]
Good call, updated.

**Comment by mightyiam** [comment]
Does this fix any filed issue?

**Comment by timothykang** [comment]
None that I could find.

I encountered the bug myself and was about to create an issue and PR with a failing test, but then thought why not just fix it while I was at it.

**Comment by JamesHenry** [comment]
Thanks a lot for your patience on this, @timothykang!

**Pull request merged**
