### PR TITLE
Fix: Treat function-type fields as fields, not methods

### LINKED ISSUE #97: typescript/member-ordering issue :
### the filed is function type
* in class
````javascript
  private _required:boolean
  private _typeChecker:(data:any)=>boolean
  constructor(validator:(data:any)=>boolean){ 
  ^^^^^^^^^^^ error
    this._required = false
    this._typeChecker = validator
  }
  check(data:any):boolean{
    if(_.isNil(data)){
      return !this._required
    }
    return this._typeChecker(data)
  }
````
````javascript
  private _required:boolean
  constructor(validator:(data:any)=>boolean){ 
    this._required = false
    this._typeChecker = validator
  }
 private _typeChecker:(data:any)=>boolean
 ^^^^^^^ error
  check(data:any):boolean{
    if(_.isNil(data)){
      return !this._required
    }
    return this._typeChecker(data)
  }
````
 * in eslintrc.js
````javascript
    'typescript/member-ordering': ['error', {
      'classes': [
        'field', 'constructor', 'method'
      ],
    }],
````
The field should be a filed not method

### PR DESCRIPTION
**Pull request by macklinu**
Resolves #97 - see discussion in that issue.

### CODE REVIEW

**Comment by corbinu** [comment]
Looks good to me

**Comment by macklinu** [comment]
I use VSCode with the Prettier plugin, and by saving the `member-ordering.md` file in 45360d2, Prettier formatted that file. I made another tweak to the formatting in 92580cc - let me know if I should move these changes into another PR, as there was technically no documentation that needed to be changed (just fixed a couple of typos).

**Comment by corbinu** [comment]
I believe James would rather it be in a separate PR labeled "Chore". Thats just based on watching how the eslint team does things however.

**Comment by macklinu** [comment]
Makes sense, I'll amend this PR and open another PR 🙂

**Pull request merged**
