### PR TITLE
add valid type-annotation-spacing test code

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
This should be valid and passing, I think.

**Comment by weirdpattern** [comment]
The code that fixes this hasn't been merged yet, this should be valid once #80 has been merged.

**Comment by mightyiam** [comment]
Cool.

Suggestion: if this valid test code is desirable, keep this PR open and merge it after #80. If not, please close this PR.

**Comment by weirdpattern** [comment]
It seems like a good test, so I would say let's keep it open, but we will have to re-run the CI build once #80 has been merged to make sure this is fixed... 

Sounds good?

**Comment by mightyiam** [comment]
@weirdpattern 

:+1: 

I will follow. I am watching this repo. I :heartbeat: this repo.

**Comment by JamesHenry** [comment]
Thanks again chaps, #80 has been merged

**Comment by mightyiam** [comment]
I guess this is not required.

**Pull request closed without merging**
