### PR TITLE
New: Add no-empty-interface

### PR DESCRIPTION
**Pull request by weirdpattern**
This includes

New rule no-empty-interface
Corresponding test
Corresponding documentation
Update to README.md to include the new rule

Related to #5 (TSLint compatibility)

### CODE REVIEW

**Comment by weirdpattern** [comment]
I will rebase this as soon as I get home...

**Comment by corbinu** [comment]
LGTM

**Comment by JamesHenry** [comment]
Thanks! The older README.md cleanup PR that went in means this just needs to be rebased before going in

**Comment by weirdpattern** [comment]
@JamesHenry Done... either @j-f1 or myself will have to rebase one or more PRs once you have merged one of these, just let us know and we will take care of it 😄

**Comment by JamesHenry** [comment]
@weirdpattern @j-f1 You're right I'm sorry about that, I'll merge them chronologically

**Pull request merged**
