### PR TITLE
Chore: Bump deps and fix errors in no-explicit-any

### LINKED ISSUE #54: no-explicit-any Broken in typescript paser 5.0.0 and greater
Just a note looks like no-explicit-any has been broken by typescript paser 5.0.0

### PR DESCRIPTION
**Pull request by corbinu**
Bumps the parser and other deps and fixes errors in no-explicit-any. Closes #54

### CODE REVIEW

**Comment by weirdpattern** [comment]
that was probably my fault, I copy-pasted the code then manually formatted it... sorry!

**Comment by j-f1** [comment]
It might be a good idea to enable [Greenkeeper](https://GitHub.com/apps/greenkeeper) to avoid having to do this in the future. It’ll automatically run your tests with the latest version of each dependency, and open an issue if an in-range dependency breaks the build. If a dependency updates out of the range specified in your package.json, you’ll get a PR to update it automatically.

**Comment by JamesHenry** [comment]
@j-f1 Greenkeeper is great but unfortunately I do not have admin access to the repo, so cannot enable such things.

**Comment by j-f1** [comment]
cc @nzakas

> Greenkeeper is great but unfortunately I do not have admin access to the repo, so cannot enable such things.

**Pull request merged**
