### PR TITLE
Add `eslint-docs` to keep rule descriptions consistent

### PR DESCRIPTION
**Pull request by j-f1**
`eslint-docs` copies the rule description from the rule’s source file to a list of rules in the README and to the top of the rule documentation file. This prevents descriptions from getting out of sync, and it could check for other patterns in the future. 

**Note**: I am the creator of the `eslint-docs` project.

### CODE REVIEW

**Comment by weirdpattern** [comment]
This looks awesome, looks like the build failed due to destructuring assignment in eslint-docs, probably because of the version of node we are targeting...

**Comment by j-f1** [comment]
I’m currently changing the project to compile down to Node.js 4-compatible code.

**Comment by j-f1** [comment]
@weirdpattern Fixed!

**Comment by JamesHenry** [comment]
Really sorry for the delay, I buried myself pretty badly for the last month and open-source had to take a back seat. Light at the end of the tunnel now! P.S. Apologies that you will see this comment multiple times 😅 

This is a neat idea, thanks @j-f1!

**Pull request merged**
